// Biome invariants and integration tests. BIOME_TANK=type limits the layout matrix.
const {load}=require('./harness');const JT=load(),B=JT.Biome;let pass=0,bad=[];const ok=(v,msg)=>v?pass++:bad.push(msg);JT.R=JT.makeRng(202614);
for(const id of JT.BIOME_ORDER){const d=JT.BIOMES[id];ok(!!d.name,id+' name');if(id!=='classic'){ok(!!JT.SUBSTRATES[d.sub],id+' ground');ok(!!JT.BACKGROUNDS[d.bg],id+' background');for(const ev of d.events)ok(!!JT.BIOME_EVENTS[ev],id+' event '+ev);for(const prey of d.prey)ok(!!JT.PREY_BY_ID[prey],id+' prey '+prey);}}
for(const s of JT.SPECIES){if(s.id!=='bold')ok(B.homesOf(s.id).length>0,s.id+' home');for(const id of B.homesOf(s.id))ok(!!JT.BIOMES[id],s.id+' biome '+id);}
for(const id of JT.BiomeContent.ids){const d=JT.DECOR_BY_ID[id];ok(!!d,id+' registered');ok(!!d.desc,id+' description');ok(!!JT.BIOMES[d.biome],id+' native');}
ok(JT.JOURNAL.filter(x=>(JT.JOURNAL_META[x.id]||[])[0]==='biomes').length===7,'seven journal entries');
const h=new JT.Habitat({type:'nano'});ok(B.id(h)==='classic','legacy biome fallback');h.data.biome='invalid';ok(B.id(h)==='classic','invalid biome fallback');
B.setBiome(h,'classic');ok(B.comfortFor('classic','peacock')===.7&&B.speedK(h,'peacock')===1&&B.tameK(h,'peacock')===1,'Classic neutral');B.setBiome(h,'desert');ok(B.comfortFor('desert','apache')===1,'native comfort');ok(B.comfortFor('desert','bold')===.75,'adaptable');ok(B.comfortFor('desert','magnolia')===.45,'out comfort');ok(B.speedK(h,'apache')===1.06&&B.tameK(h,'apache')===1.25,'home factors');ok(B.speedK(h,'magnolia')===.94&&B.tameK(h,'magnolia')===.85,'out factors');h.daylight=()=>0;ok(!B.start(h,'heat'),'heat waits for daylight');h.daylight=()=>1;ok(B.start(h,'heat'),'heat starts');ok(Math.abs(B.speedK(h,'apache')-1.166)<1e-8,'heat speed');
for(const id of JT.BIOME_ORDER.filter(x=>x!=='classic')){B.setBiome(h,id);const target=JT.BIOMES[id].hum.reduce((a,b)=>a+b)/2;h.data.humidity=target-.1;B.climate(h,10);ok(h.data.humidity>target-.1&&h.data.humidity<target,id+' humidity pull');for(const ev of JT.BIOMES[id].events){h.data.prey=[];h.data.humidity=.3;const old=h.data.humidity;ok(B.start(h,ev),id+' start '+ev);if(ev==='rain')ok(h.data.humidity>old,'rain humidity');if(['hatch','fireflies'].includes(ev))ok(h.prey.length>0,ev+' prey');const v=B.ensure(h);B.tick(h,v.until-v.clock+.01);ok(!v.id&&v.next>v.clock,id+' end '+ev);}}
const types=process.env.BIOME_TANK?[process.env.BIOME_TANK]:Object.keys(JT.HABITATS);let layouts=0;for(const type of types)for(const id of JT.BIOME_ORDER.filter(x=>x!=='classic')){const tank=new JT.Habitat({type});try{B.layout(tank,id,73);layouts++;ok(tank.decor.length>=3,type+' '+id+' minimum decor');ok(tank.data.substrate===JT.BIOMES[id].sub,type+' '+id+' ground');ok(tank.data.bg===JT.BIOMES[id].bg,type+' '+id+' background');ok(tank.decor.every(x=>B.suit(JT.DECOR_BY_ID[x.type],id)>0),type+' '+id+' compatible');if(id==='paludarium'){ok(B.ponds(tank).length>0,type+' pond');for(const d of B.ponds(tank)){const g=tank.geoms[d.id];ok(g.tops.length===0,'no pond tops');ok(g.water.every(w=>w.floor),'floor drinking');ok(!JT.SpiderAI.nestSiteOK(tank,{k:'floor'},[d.x,0,d.z],3),'no pond nest');}ok(tank.nav.water.some(w=>w.floor),'reachable floor water');}const sp=tank.addSpider(B.natives(id)[0]||'bold',{stage:2});for(let i=0;i<60;i++)tank.update(1/30,true);ok(sp.pos.every(Number.isFinite),type+' '+id+' finite simulation');}catch(e){bad.push(type+' '+id+' '+e.stack);}}
const game=new JT.Game();game.newGame();const gh=game.hab;B.setBiome(gh,'heath');const sp=gh.spiders[0];sp.homeT=JT.DAY-2;B.comfort(gh,2);ok(!!game.state.journal.settledIn,'settledIn journal');for(const id of ['rainforest','desert','paludarium','nightmoss']){const t=game.createHabitat('nano');B.setBiome(t,id);}game.checkUnlocks();ok(!!game.state.journal.biomeTour,'biomeTour journal');const paused=game.habs[1];B.ensure(paused);const before=paused.data.bev.clock;game.tick(.1);ok(paused.data.bev.clock===before,'offscreen weather paused');console.log(JSON.stringify({pass,fail:bad.length,layouts,type:process.env.BIOME_TANK||'all',bad}));if(bad.length)process.exitCode=1;
